version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GPTZERO_API_KEY=${GPTZERO_API_KEY}
    volumes:
      - ./data:/usr/src/app/data
